sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
  - 9
os:
  - linux
before_script:
  - npm test
  - npm run lint
after_success:
  - npm install codecov -g
  - npm run postcover
